### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by iwarsong** [BugScanTeam/DNSLog#2]
# NS域名
  NS1_DOMAIN = 'ns1.a.com'
  NS2_DOMAIN = 'ns2.b.com'

应该是
 NS1_DOMAIN = 'ns1.a.com'
  NS2_DOMAIN = 'ns2.a.com'

吧？

**Comment by Medicean** [comment]
@iwarsong  是的，笔误 = =  感谢指正

**Comment by iwarsong** [comment]
正在在自己的服务器上搭建试试~必须给这种开源精神赞一个~现在就在等DNS同步了……o(∩_∩)o
