### ISSUE TITLE
查询dns解析记录api

### ISSUE THREAD

**Issue by c26root** [BugScanTeam/DNSLog#5]
方便直接查询解析记录 JSON最好

**Comment by Medicean** [comment]
@c26root 

> 此功能仅在 [BugScan DNSLog](http://admin.dnslog.link) 中更新

查询所有hashstr时，只需要将 hashstr 设置为 udomain 即可查询该 udomain 的所有解析记录。

eg:

查询 test 的所有 web 记录

http://admin.dnslog.link/api/web/test/test/
