### ISSUE TITLE
域名解析的问题

### ISSUE THREAD

**Issue by ResidualLaugh** [BugScanTeam/DNSLog#6]
1.按照说明修改完setting.py
2.在云解析上修改了ns记录

可是无法使用
导致走了很多弯路，让我误以为是本地dns服务出了问题

**Comment by ResidualLaugh** [comment]
今天翻看了一下zoneresolver.py的代码，发现是新起了一个dns服务，所以猜想是本地的dns服务影响到了，通过`sudo /etc/init.d/bind9 stop`  停止了本地的服务，然后启动dnslog，发现终于成功了。。。

**Comment by howmp** [comment]
[](https://ws3.sinaimg.cn/large/9150e4e5ly1fkwh1iv1e7g206o06oq30.gif)

**Comment by howmp** [comment]
![image](https://user-images.githubusercontent.com/10806806/32218230-3e83c0de-be65-11e7-8ec0-bdf92e651d2f.png)

**Comment by ResidualLaugh** [comment]
mmp，我为了提示一下未来走上相同弯路的有缘人

**Comment by Medicean** [comment]
![](https://user-images.githubusercontent.com/10806806/32218230-3e83c0de-be65-11e7-8ec0-bdf92e651d2f.png)
