### ISSUE TITLE
我想问下dnslog搭建完成之后密码错误怎么回事啊

### ISSUE THREAD

**Issue by cuijianxiong** [BugScanTeam/DNSLog#7]
我想问下dnslog搭建完成之后密码错误怎么回事啊

改了好几次密码还是显示错误~~~

**Comment by howmp** [comment]
https://docs.djangoproject.com/en/1.11/ref/django-admin/#django-contrib-auth

尝试修改密码，或者重新创建一个管理员用户

**Comment by cuijianxiong** [comment]
@howmp 问题找到了  这个是django管理后台 不是前台~~~
